export enum ScreenId {
  // Observe
  DASHBOARD = 'DASHBOARD',
  TELEMETRY = 'TELEMETRY',
  ANALYTICS = 'ANALYTICS',
  DASHBOARD_EXEC_SUMMARY = 'DASHBOARD_EXEC_SUMMARY',
  DASHBOARD_PRODUCTION = 'DASHBOARD_PRODUCTION',
  DASHBOARD_QUALITY = 'DASHBOARD_QUALITY',
  DASHBOARD_LOGISTICS = 'DASHBOARD_LOGISTICS',
  DASHBOARD_RISK_COMPLIANCE = 'DASHBOARD_RISK_COMPLIANCE',
  TELEMETRY_LIVE_VIEW = 'TELEMETRY_LIVE_VIEW',
  TELEMETRY_HISTORY_VIEW = 'TELEMETRY_HISTORY_VIEW',
  TELEMETRY_EXPORT = 'TELEMETRY_EXPORT',
  ANALYTICS_OVERVIEW_TAB = 'ANALYTICS_OVERVIEW_TAB',
  ANALYTICS_BATCH_TAB = 'ANALYTICS_BATCH_TAB',
  ANALYTICS_STATION_TAB = 'ANALYTICS_STATION_TAB',
  ANALYTICS_QUALITY_TAB = 'ANALYTICS_QUALITY_TAB',
  ANALYTICS_LOCATION_TAB = 'ANALYTICS_LOCATION_TAB',
  ANALYTICS_REPORTS_TAB = 'ANALYTICS_REPORTS_TAB',
  ANALYTICS_EXPORT = 'ANALYTICS_EXPORT',

  // Design
  SKU_LIST = 'SKU_LIST',
  /* Added SKU_DETAIL to fix ScreenId.SKU_DETAIL does not exist error */
  SKU_DETAIL = 'SKU_DETAIL',

  // Trace
  CELL_LOTS_LIST = 'CELL_LOTS_LIST',
  CELL_LOTS_CREATE = 'CELL_LOTS_CREATE',
  CELL_LOTS_DETAIL = 'CELL_LOTS_DETAIL',
  LINEAGE_VIEW = 'LINEAGE_VIEW',

  // Operate
  BATCHES_LIST = 'BATCHES_LIST',
  BATCHES_CREATE = 'BATCHES_CREATE',
  BATCHES_DETAIL = 'BATCHES_DETAIL',
  BATTERIES_LIST = 'BATTERIES_LIST',
  BATTERIES_DETAIL = 'BATTERIES_DETAIL',
  PROVISIONING = 'PROVISIONING', 
  PROVISIONING_STATION_SETUP = 'PROVISIONING_STATION_SETUP',
  PROVISIONING_QUEUE = 'PROVISIONING_QUEUE',
  INVENTORY = 'INVENTORY',
  /* Added INVENTORY_DETAIL to fix ScreenId.INVENTORY_DETAIL does not exist error */
  INVENTORY_DETAIL = 'INVENTORY_DETAIL',
  DISPATCH = 'DISPATCH', 
  DISPATCH_LIST = 'DISPATCH_LIST',
  DISPATCH_DETAIL = 'DISPATCH_DETAIL',

  // Assembly Workflow
  MODULE_ASSEMBLY_LIST = 'MODULE_ASSEMBLY_LIST',
  MODULE_ASSEMBLY_DETAIL = 'MODULE_ASSEMBLY_DETAIL',
  PACK_ASSEMBLY_LIST = 'PACK_ASSEMBLY_LIST',
  PACK_ASSEMBLY_DETAIL = 'PACK_ASSEMBLY_DETAIL',
  
  // Assure (S7-S8)
  EOL_QA_QUEUE = 'EOL_QA_QUEUE', 
  EOL_SETUP = 'EOL_SETUP',
  EOL_REVIEW = 'EOL_REVIEW',
  EOL_DETAILS = 'EOL_DETAILS',
  EOL_RUN_TEST = 'EOL_RUN_TEST',
  EOL_AUDIT_DETAIL = 'EOL_AUDIT_DETAIL',
  
  // Govern
  COMPLIANCE = 'COMPLIANCE',
  CUSTODY = 'CUSTODY',
  CUSTODY_OVERVIEW = 'CUSTODY_OVERVIEW',
  CUSTODY_LIST = 'CUSTODY_LIST',
  CUSTODY_EXCEPTIONS = 'CUSTODY_EXCEPTIONS',
  CUSTODY_RECEIVE_ACTION = 'CUSTODY_RECEIVE_ACTION',
  CUSTODY_ACCEPT_REJECT_ACTION = 'CUSTODY_ACCEPT_REJECT_ACTION',
  COMPLIANCE_DPP_PREVIEW = 'COMPLIANCE_DPP_PREVIEW',
  COMPLIANCE_SUSTAINABILITY_PREVIEW = 'COMPLIANCE_SUSTAINABILITY_PREVIEW',
  COMPLIANCE_RECYCLING_PREVIEW = 'COMPLIANCE_RECYCLING_PREVIEW',
  COMPLIANCE_REG_EXPORT_PREVIEW = 'COMPLIANCE_REG_EXPORT_PREVIEW',
  COMPLIANCE_OVERVIEW_TAB = 'COMPLIANCE_OVERVIEW_TAB',
  COMPLIANCE_CHECKS_TAB = 'COMPLIANCE_CHECKS_TAB',
  COMPLIANCE_FINDINGS_TAB = 'COMPLIANCE_FINDINGS_TAB',
  COMPLIANCE_EVIDENCE_TAB = 'COMPLIANCE_EVIDENCE_TAB',
  COMPLIANCE_AUDIT_TRAIL_TAB = 'COMPLIANCE_AUDIT_TRAIL_TAB',
  COMPLIANCE_FUTURE_TAB = 'COMPLIANCE_FUTURE_TAB',
  COMPLIANCE_FINDINGS_EDIT = 'COMPLIANCE_FINDINGS_EDIT',

  // Resolve
  WARRANTY = 'WARRANTY',
  WARRANTY_OVERVIEW = 'WARRANTY_OVERVIEW',
  WARRANTY_CLAIMS_LIST = 'WARRANTY_CLAIMS_LIST',
  WARRANTY_EXTERNAL_INTAKE = 'WARRANTY_EXTERNAL_INTAKE',
  WARRANTY_CREATE_CLAIM_INTERNAL = 'WARRANTY_CREATE_CLAIM_INTERNAL',
  WARRANTY_UPDATE_CLAIM_INTERNAL = 'WARRANTY_UPDATE_CLAIM_INTERNAL',
  WARRANTY_DECIDE_DISPOSITION = 'WARRANTY_DECIDE_DISPOSITION',
  WARRANTY_CLOSE_CLAIM = 'WARRANTY_CLOSE_CLAIM',
  WARRANTY_EXPORT = 'WARRANTY_EXPORT',

  // Admin
  SETTINGS = 'SETTINGS',
  SETTINGS_PROFILE = 'SETTINGS_PROFILE',
  SETTINGS_USERS = 'SETTINGS_USERS',
  SETTINGS_API_KEYS = 'SETTINGS_API_KEYS',
  SETTINGS_NOTIFICATIONS = 'SETTINGS_NOTIFICATIONS',
  SETTINGS_WEBHOOKS = 'SETTINGS_WEBHOOKS',
  SETTINGS_EXPORT = 'SETTINGS_EXPORT',
  RBAC_VIEW = 'RBAC_VIEW',

  // Guided
  RUNBOOK_HUB = 'RUNBOOK_HUB',
  RUNBOOK_DETAIL = 'RUNBOOK_DETAIL',

  // Diagnostics
  SYSTEM_HEALTH = 'SYSTEM_HEALTH'
}

export const SCREEN_GROUPS = {
  GUIDED: [ScreenId.RUNBOOK_HUB],
  OBSERVE: [ScreenId.DASHBOARD, ScreenId.TELEMETRY, ScreenId.ANALYTICS],
  DESIGN: [ScreenId.SKU_LIST],
  TRACE: [ScreenId.CELL_LOTS_LIST, ScreenId.CELL_LOTS_CREATE, ScreenId.CELL_LOTS_DETAIL, ScreenId.LINEAGE_VIEW],
  OPERATE: [
    ScreenId.BATCHES_LIST, 
    ScreenId.MODULE_ASSEMBLY_LIST,
    ScreenId.PACK_ASSEMBLY_LIST,
    ScreenId.BATTERIES_LIST, 
    ScreenId.PROVISIONING_QUEUE,
    ScreenId.PROVISIONING_STATION_SETUP, 
    ScreenId.INVENTORY, 
    ScreenId.DISPATCH_LIST
  ],
  ASSURE: [ScreenId.EOL_QA_QUEUE, ScreenId.EOL_SETUP, ScreenId.EOL_REVIEW],
  RESOLVE: [ScreenId.WARRANTY],
  GOVERN: [ScreenId.COMPLIANCE, ScreenId.CUSTODY],
  ADMIN: [ScreenId.SETTINGS, ScreenId.RBAC_VIEW],
};